site_name: Ryan Morshead

site_dir: site
docs_dir: docs

theme:
  icon:
    logo: material/account-circle
  name: "material"
  font:
    text: 'Exo'
    code: 'Fira Mono'
  palette:
    primary: 'white'
    accent: 'indigo'

plugins:
- pdf-export
- search

markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
- Home: index.md
- Projects: projects.md
- Resume: resume.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: 'https://github.com/rmorshea'
  - icon: fontawesome/brands/twitter
    link: 'https://twitter.com/rmorshea'
  - icon: fontawesome/brands/linkedin
    link: 'https://linkedin.com/in/rmorshea'
